### ISSUE TITLE
安卓支持

### ISSUE THREAD

**Issue by ddkwork** [zrcoder/amisgo#1]
你好，有计划支持安卓吗？我之前使用gioui的webview加载html三件套是正常的
![Screenshot_20240821_121232_localhost.demowebviewer.jpg](https://github.com/user-attachments/assets/aba39f8d-282f-43aa-a135-cbf3e5e20040)

**Comment by zrcoder** [comment]
应该是天然支持的。响应式布局，自动适应各种设备尺寸。

比如readme里的hello world，我没有在手机上测试，但是电脑上拖动缩放浏览器大小，页面是自动适应的，比如右下角那个按钮，在宽度较小时会占据整个底部。

**Comment by ddkwork** [comment]
您方便抽空把demo的事件交互做一些例子吗？比如hello word demo里面的两个编辑框oninput等事件发生的时候，go通过回调或者信道获取控件输入输出，以便和go代码交互，谢谢。

**Comment by zrcoder** [comment]
好的，这个正好在ReadMe的TODO列表里。不过我的节奏可能较慢，平时要忙别的。

如果着急，可以直接看 Amis https://aisuda.bce.baidu.com/amis/zh-CN/docs/index 的文档， amisgo 是对其对一层包装。

**Comment by ddkwork** [comment]
不急，等你哟



---原始邮件---
发件人: "Rangding ***@***.***&gt;
发送时间: 2024年8月21日(周三) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zrcoder/amisgo] 安卓支持 (Issue #1)




 
好的，这个正好在ReadMe的TODO列表里。不过我的节奏可能较慢，平时要忙别的。
 
如果着急，可以直接看 Amis https://aisuda.bce.baidu.com/amis/zh-CN/docs/index 的文档， amisgo 是对其对一层包装。

**Comment by ddkwork** [comment]
https://github.com/wcharczuk/json2go/blob/main/main.go

我试了这个，只需小修即可工作

**Comment by zrcoder** [comment]
> https://github.com/wcharczuk/json2go/blob/main/main.go
> 
> 我试了这个，只需小修即可工作

@ddkwork 没有太懂你的做法。另外，这个话题的讨论我另开了讨论主题，可以移步交流：https://github.com/zrcoder/amisgo/discussions/2
