### ISSUE TITLE
appData dir

### ISSUE THREAD

**Issue by ddkwork** [zrcoder/amisgo#3]
copy fyne的app数据存储目录实现代码，为所有平台提供数据缓存目录。

对于安卓，apk的安装目录为根目录，在里面创建目录和文件应该不需要申请存储权限?不确定，有待测试。

应用场景:
todolist app本地存储，
日志文件存储，
等等。。。

https://github.com/fyne-io/fyne/blob/master/app%2Fapp_mobile_and.go#L48-L56

**Comment by zrcoder** [comment]
基本上，百度 amis 和 这里的 amisgo 不是做 native app的，仅写web app，至于存储等是需要放到后端，前端通过 api 的方式来调用。

当然，借助 amis，生成 html页面，然后用webview等包装成安卓的本地应用，也可以。但基本做不了什么事情，除非你有一个api 服务器。
